### ISSUE TITLE
git will fail after cancel

### ISSUE THREAD

**Issue by SplitGemini** [seeraven/gitcache#13]
When using ctrl+c to cancel the operation of cloning from the remote, the following clone will always fail.

I found a db.lock at my GITCACHE_DIR, 

Trace back as follows:
```text
Traceback (most recent call last):
  File "/gitcache/git", line 40, in <module>
    handle_git_command(sys.argv[0:1], sys.argv[1:])
  File "/gitcache/git_cache/git_command.py", line 95, in handle_git_command
    sys.exit(git_clone(git_options))
  File "/gitcache/git_cache/commands/clone.py", line 53, in git_clone
    return mirror.clone_from_mirror(git_options)
  File "/gitcache/git_cache/git_mirror.py", line 270, in clone_from_mirror
    if not self.update(ref):
  File "/gitcache/git_cache/git_mirror.py", line 150, in update
    return self._update(ref)
  File "/gitcache/git_cache/git_mirror.py", line 398, in _update
    self.database.save_update_time(self.path)
  File "/gitcache/git_cache/database.py", line 92, in save_update_time
    self.database[path]["last-update-time"] = time.time()
KeyError: '/git_cache/mirrors/github.com/seeraven/gitcache'
``` 

I think it may be necessary to handle signal。

**Comment by seeraven** [comment]
Thanks for your issue report. The bug is actually triggered by a mismatch between the mirror directory (which was already created) and the database (which did not record the mirror as the clone was aborted). I added a new test and published a new release https://github.com/seeraven/gitcache/releases/tag/v1.0.11 
Can you test the new version?

**Comment by SplitGemini** [comment]
Thank you, I will test at this weekend.

**Comment by SplitGemini** [comment]
It works perfectly.
